name: Python

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        python -m pip install pip;
        pip install maturin;
        maturin build;
        pip install target/wheels/*.whl;
